'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowUpRight,AudioLines,ChartNoAxesCombined,FileSpreadsheet,Mic,Plus,Square,Volume2,VolumeX,X} from 'lucide-react';
import RequestToast from './request-toast';
import {readQueryResponse} from '@/lib/query-progress';
import PerformancePanel from './performance-panel';
import {Measurements,now} from '@/lib/measurements';
import {AudioObserver} from '@/lib/audio-observer';
import GeneratedChart from './generated-chart';
import {GeminiLive} from '@/lib/gemini-live';
import {analyticsInstructions,screenTool,screenResult,transitionScreen,type Screen} from '@/lib/analytics';
import {checkUploadLimit,parseUploads,uploadSchema,evaluateQuery,type UploadSet} from '@/lib/upload-data';
import './analytics.css';
const DEMO_API='https://decisionos.me/analytics/api/demo';
export default function Analytics(){
 const [activity,setActivity]=useState<{step:number;error?:string;detail?:string}|null>(null);
 useEffect(()=>{if(activity?.step!==5&&!activity?.error)return;const timer=setTimeout(()=>setActivity(null),activity.error?7000:3500);return()=>clearTimeout(timer);},[activity]);
 const [metadata,setMetadata]=useState<any>(null),[queryMetrics,setQueryMetrics]=useState<any>(null),[,refreshMetrics]=useState(0);
 const [screen,setScreen]=useState<Screen>({view:'sales',details:[],empty:true}),[uploads,setUploads]=useState<UploadSet|null>(null),[status,setStatus]=useState('off'),[text,setText]=useState(''),[answer,setAnswer]=useState('Ask a question, or upload your data to begin.'),[error,setError]=useState(''),[heard,setHeard]=useState(''),[muted,setMuted]=useState(false),[reduced,setReduced]=useState(false),[busy,setBusy]=useState(false),[progress,setProgress]=useState<{value:number;label:string}|null>(null),[prompts,setPrompts]=useState(false);
 const current=useRef(screen),data=useRef(uploads),live=useRef<GeminiLive|null>(null),media=useRef<MediaStream|null>(null),epoch=useRef(0),request=useRef(0),mute=useRef(false),fileInput=useRef<HTMLInputElement>(null),pending=useRef(''),folderInput=useRef<HTMLInputElement>(null),observer=useRef<AudioObserver|null>(null),measure=useRef<Measurements|null>(null);if(!measure.current){measure.current=new Measurements();measure.current.model='gemini-3.8-live';}const m=measure.current;current.current=screen;data.current=uploads;
 function stop(){m.finish();observer.current?.close();observer.current=null;epoch.current++;live.current?.close();live.current=null;media.current?.getTracks().forEach(t=>t.stop());media.current=null;setStatus('off');}
 useEffect(()=>{m.onChange=()=>refreshMetrics(v=>v+1);folderInput.current?.setAttribute('webkitdirectory','');void fetch(DEMO_API+'/metadata').then(r=>r.json()).then(setMetadata).catch(()=>{});const q=matchMedia('(prefers-reduced-motion: reduce)');setReduced(q.matches);const change=()=>setReduced(q.matches);q.addEventListener('change',change);return()=>{q.removeEventListener('change',change);request.current++;epoch.current++;observer.current?.close();live.current?.close();media.current?.getTracks().forEach(t=>t.stop());};},[]);
 function commit(args:unknown,source?:'uploaded'){const next={...transitionScreen(current.current,args),source};current.current=next;setScreen(next);setError('');return {...screenResult(next),source};}
 async function analyze(message:string){const id=++request.current,files=data.current;const {t,call}=m.call('query_analytics',{message},files?'uploaded':'duckdb');setBusy(true);setActivity({step:1,detail:'Turning your question into a query using the table schema.'});setError('');setAnswer('Working on your question…');try{const base=location.pathname.startsWith('/analytics')?'/analytics':'';const response=await fetch(files?base+'/api/analytics':DEMO_API+'/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,stream:!files,context:files?current.current.generated||null:(current.current as any).queryContext||null,source:files?uploadSchema(files):null})});const result=await readQueryResponse(response,(step,detail)=>{if(id===request.current)setActivity({step,detail});});if(id!==request.current)return {superseded:true};if(!response.ok)throw Error(result.error||'Please try again.');if(files)setActivity({step:2,detail:'Applying the generated query to your uploaded rows.'});const action=files?evaluateQuery(files,result.queryPlan):result;setActivity({step:4,detail:`Displaying ${action.generated?.title||'your answer'} as a ${action.display==='number'?'single number':action.display==='table'?'table':(action.generated?.kind||'chart')+' chart'}.`});const rendered=commit(action,files?'uploaded':undefined);if(!files){(current.current as any).queryContext={sql:result.sql,kind:result.generated.kind,display:result.display,title:result.generated.title};setQueryMetrics(result.metrics);}else setQueryMetrics(null);m.result(t,call,{rows:action.generated?.points?.length},true);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));m.mark('visibleAction',now(),'committed page paint',t);if(!live.current)m.finish();if(id!==request.current)return {superseded:true};setActivity({step:5,detail:`${action.generated?.title||'Your answer'} is now on screen.`});setAnswer('Your answer is on screen.');return rendered;}catch(e){m.result(t,call,{error:e instanceof Error?e.message:'Query failed'},false);if(id===request.current){setActivity({step:0,error:e instanceof Error?e.message:'Please try again.'});setError(e instanceof Error?e.message:'Please try again.');setAnswer('I couldn’t finish that query. Please try again.');}throw e;}finally{if(id===request.current)setBusy(false);}}
 async function executeTool(args:unknown){const a=args as Record<string,unknown>;const query=typeof a.query==='string'?a.query:pending.current;if(!query)throw Error('Call show_analytics with the user question in query. The server computes answers from the database or uploaded rows.');return analyze(query);}
 const executeRef=useRef(executeTool);executeRef.current=executeTool;
 useEffect(()=>{const mc=(navigator as any).modelContext||(document as any).modelContext;if(!mc?.registerTool)return;const c=new AbortController();Promise.resolve(mc.registerTool({name:screenTool.name,description:screenTool.description,inputSchema:screenTool.parameters,execute:async(args:unknown)=>({content:[{type:'text',text:JSON.stringify(await executeRef.current(args))}]})},{signal:c.signal})).catch(()=>{});return()=>{c.abort();mc.unregisterTool?.(screenTool.name);};},[]);
 async function start(){if(live.current)return;const generation=++epoch.current;setStatus('connecting');setError('');try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(epoch.current!==generation){stream.getTracks().forEach(t=>t.stop());return;}media.current=stream;observer.current=new AudioObserver(stream,m,()=>!mute.current);let input='',output='',visualized=false;const session=new GeminiLive('gemini-3.8-live',{profile:{instructions:'You are a concise ecommerce analyst. All answers MUST use show_analytics with query containing the exact user question. Never invent numbers or supply generated data. The tool reads the schema and queries DuckDB, or computes uploaded files. Discuss only returned values. Prefer time series except a specific date should display a number. Use the schema and rules in context. After a tool succeeds give one brief observation, then listen. Stop only on explicit request.',tool:screenTool,context:()=>({demoSchema:metadata,uploadedDataAvailable:!!data.current,tables:data.current?uploadSchema(data.current):null,current:current.current.empty?null:screenResult(current.current)}),greeting:'Briefly greet the user and ask what they want to explore. Do not change the screen.'},execute:async(name,args)=>{if(name==='stop_listening'){stop();return {stopped:true};}if(name!=='show_analytics')throw Error('Unknown tool');visualized=true;const result=await executeRef.current(typeof args==='string'?JSON.parse(args):args);pending.current='';return result;},status:s=>{if(epoch.current===generation)setStatus(s);},input:s=>{m.input(s);if(!input){visualized=false;setActivity({step:0,detail:'Listening to your question and identifying the data you need.'});}input+=s;pending.current=input;output='';setHeard(input);},complete:()=>{m.mark('providerComplete',now(),'gemini');m.scheduleFinish();const q=input||pending.current;if(q&&!visualized)void analyze(q).catch(()=>{});pending.current='';input='';visualized=false;},output:s=>{m.output(s);output+=s;setAnswer(output);},error:s=>{if(epoch.current===generation){stop();setError(s);}},ready:()=>{if(epoch.current===generation)setStatus('listening');},muted:()=>mute.current,outputStream:stream=>observer.current?.observeOutput(stream)});live.current=session;await session.connect(stream);}catch(e){if(epoch.current===generation){stop();setError(e instanceof Error?e.message:'Could not connect.');}}}
 function ask(message:string){if(!message.trim()||progress)return;m.begin('text',message);setText('');setHeard(message);setActivity({step:0,detail:'Listening to your question and identifying the data you need.'});setPrompts(false);setError('');if(live.current?.ready){request.current++;pending.current=message;live.current.text(message);setStatus('thinking');return;}void analyze(message).catch(()=>{});}
 async function upload(files:File[]){if(!files.length){setError('No CSV or Excel files were found in that selection.');return;}setError('');try{checkUploadLimit(files,data.current?.bytes||0);request.current++;setActivity(null);setBusy(false);stop();setProgress({value:0,label:'Preparing files'});const loaded=await parseUploads(files,data.current,(value,label)=>setProgress({value,label}));data.current=loaded;setUploads(loaded);const blank:Screen={view:'sales',details:[],empty:true};current.current=blank;setScreen(blank);setAnswer('Your data is ready. What would you like to know?');setHeard('');setQueryMetrics(null);}catch(e){setError(e instanceof Error?e.message:'Unable to read those files.');}finally{setProgress(null);if(fileInput.current)fileInput.current.value='';if(folderInput.current)folderInput.current.value='';}}
 function clear(){setActivity(null);request.current++;stop();setBusy(false);data.current=null;setUploads(null);setScreen({view:'sales',details:[],empty:true});setError('');setAnswer('Ask a question, or upload your data to begin.');}
 const sampleQuestions=uploads?['Show a daily trend using my data','Show the total for the latest date','Show a breakdown as a pie chart']:['Show daily sales for the last 30 days','Show sales for December 15, 2025','Show sales by region as a pie chart'];
 return <div className="analytics-app"><header className="an-top"><a className="an-brand" href="#"><span className="an-mark"><ChartNoAxesCombined size={21}/></span>meridian<span className="an-brand-detail">/ live analyst</span></a><div className="an-top-right"><input ref={fileInput} className="an-file-input" type="file" accept=".csv,.xlsx,.xls" multiple onChange={e=>void upload(Array.from(e.target.files||[]))} aria-label="Upload CSV or Excel files"/><input ref={folderInput} className="an-file-input" type="file" multiple onChange={e=>void upload(Array.from(e.target.files||[]).filter(f=>/\.(csv|xlsx|xls)$/i.test(f.name)))} aria-label="Upload folder of CSV or Excel files"/><button className="an-folder-button" disabled={!!progress} onClick={()=>folderInput.current?.click()}>Upload folder</button><button className="an-upload-button" disabled={!!progress} onClick={()=>fileInput.current?.click()}><Plus size={17}/> Upload data</button><a className="an-project-label" href="https://decisionos.me/projects/analytics.html">CASE STUDY ↗</a></div></header>
 <main className="an-main"><div className="an-heading"><div><p className="an-kicker">A CONVERSATION WITH YOUR DATA</p><h1>Ask a question. <span>See the answer.</span></h1></div><span className="an-demo">{uploads?'YOUR DATA':'DEMO E-COMMERCE'}</span></div>
 {!uploads&&<div className="an-demo-summary">{metadata?`${metadata.totalRows.toLocaleString()} rows · ${metadata.tables.length} tables · ${(metadata.databaseBytes/1000000).toFixed(1)} MB · Jan–Dec 2025`:'Connecting to the demo database…'} <span>Cloud DuckDB</span></div>}
 <div className="an-data-toolbar"><span>CSV & Excel · 10 MB total maximum</span>{uploads&&<button onClick={clear}>Switch to demo</button>}<button onClick={()=>setPrompts(!prompts)}>Example questions ↗</button></div>
 {uploads&&<div className="an-file-list"><FileSpreadsheet size={17}/><span>{uploads.files.join(' · ')}<small>{uploads.tables.reduce((n,t)=>n+t.rows.length,0).toLocaleString()} rows · {uploads.tables.length} tables · {(uploads.bytes/1000000).toFixed(2)} MB</small></span><button aria-label="Remove uploaded data" onClick={clear}><X size={18}/></button></div>}
 {progress&&<div className="an-upload-progress" role="status"><span>{progress.label}</span><progress max={100} value={progress.value}/><span>{progress.value}%</span></div>}
 {prompts&&<div className="an-prompt-chips">{sampleQuestions.map(q=><button key={q} onClick={()=>ask(q)}>{q}<ArrowUpRight size={15}/></button>)}</div>}
 <div className="an-answer-layout"><section className={`an-stage ${screen.empty?'an-empty':''}`} aria-label="Analytics answer" aria-busy={busy||!!progress} key={screen.empty?'empty':JSON.stringify(screen)}>{screen.empty?<div className="an-empty-content"><ChartNoAxesCombined size={32}/><h2>{uploads?'Ready when you are.':'Your next insight starts here.'}</h2><p>{uploads?'Ask about your files. The answer will appear here.':'Upload your data, or ask a question to explore a live demo.'}</p></div>:screen.generated?<GeneratedChart data={screen.generated} display={screen.display} reduced={reduced} uploaded={screen.source==='uploaded'}/>:null}{busy&&<div className="an-loading" role="status"><span/>Analyzing your question</div>}</section><PerformancePanel turns={m.turns} query={queryMetrics}/></div>
 <p className="an-data-note">{uploads?'Files stay in this browser session. Column names and query context are sent to Gemini; calculations use all your rows locally.':'Demo e-commerce · synthetic 2025 records stored in cloud DuckDB. Ask a question or upload your own files.'}</p>
 <section className="an-assistant" aria-label="Live analyst"><button className={`an-orb ${status}`} disabled={!!progress} onClick={()=>status==='off'?void start():stop()} aria-label={status==='off'?'Start live voice analyst':'Stop live voice analyst'}><span className="an-orb-core"/>{status==='off'?<Mic size={23}/>:status==='connecting'?<AudioLines size={23}/>:<Square size={19}/>}</button><div className="an-conversation"><div className="an-voice-label">{status==='off'?'YOUR LIVE ANALYST':status.toUpperCase()}<span>Gemini 3.8 Live</span></div><p aria-live="polite">{answer}</p>{heard&&<small>You: {heard}</small>}{error&&<p role="alert" className="an-error">{error}</p>}<form onSubmit={e=>{e.preventDefault();ask(text);}}><input aria-label="Ask your analytics question" placeholder={uploads?'Ask about your data…':'Ask anything about your business…'} value={text} onChange={e=>setText(e.target.value)}/><button aria-label="Submit question" disabled={!text.trim()||!!progress}><ArrowUp size={19}/></button></form></div><button className="an-mute" aria-label={muted?'Unmute analyst':'Mute analyst'} aria-pressed={muted} onClick={()=>{mute.current=!muted;setMuted(!muted);live.current?.mute(!muted);}}>{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button></section></main><RequestToast activity={activity} dismiss={()=>setActivity(null)}/></div>;
}
