import {DuckDBInstance} from '@duckdb/node-api';
import {mkdir,stat,writeFile} from 'node:fs/promises';
const dir=process.env.DATA_DIR||'data';await mkdir(dir,{recursive:true});
const db=await DuckDBInstance.create(`${dir}/ecommerce.duckdb`,{threads:'4',memory_limit:'1GB'});const c=await db.connect();const start=performance.now();
const sqls=[
`CREATE OR REPLACE TABLE regions AS SELECT i::INTEGER region_id, list_extract(['North America','United Kingdom','Western Europe','Eastern Europe','East Asia','South Asia','Southeast Asia','Oceania','Latin America','Middle East & Africa'],i) region_name FROM range(1,11)t(i)`,
`CREATE OR REPLACE TABLE categories AS SELECT i::INTEGER category_id, 'Category '||i category_name, list_extract(['Apparel','Electronics','Home','Beauty','Sport','Food','Books','Toys'],1+(i-1)%8) department FROM range(1,41)t(i)`,
`CREATE OR REPLACE TABLE products AS SELECT i::INTEGER product_id, 'Product '||lpad(i::VARCHAR,5,'0') product_name, ((1+hash(i)%40)::BIGINT)::INTEGER category_id, round(9+(hash(i+17)%24000)/100.0,2)::DECIMAL(12,2) list_price, round(4+(hash(i+31)%4000)/100.0,2)::DECIMAL(12,2) unit_cost FROM range(1,50001)t(i)`,
`CREATE OR REPLACE TABLE customers AS SELECT i::INTEGER customer_id, 'Customer '||lpad(i::VARCHAR,6,'0') customer_name, ('customer'||i||'@example.test') email, ((1+hash(i+41)%10)::BIGINT)::INTEGER region_id, (DATE '2024-01-01'+(hash(i+77)%366)::INTEGER) signup_date, list_extract(['consumer','business','loyalty'],(1+hash(i+99)%3)::BIGINT) segment FROM range(1,150001)t(i)`,
`CREATE OR REPLACE TABLE calendar AS SELECT d::DATE date, year(d)::INTEGER calendar_year, month(d)::INTEGER month_number, day(d)::INTEGER day_number, strftime(d,'%A') weekday, quarter(d)::INTEGER quarter_number FROM generate_series(DATE '2025-01-01',DATE '2025-12-31',INTERVAL 1 DAY)t(d)`,
`CREATE OR REPLACE TABLE order_items AS SELECT i::INTEGER order_item_id, (1+((i-1)//3))::INTEGER order_id,p.product_id, ((1+hash(i+121)%3)::BIGINT)::INTEGER quantity, p.list_price unit_price, round(p.list_price*((1+hash(i+121)%3)::BIGINT)*(hash(i+181)%21)/100.0,2)::DECIMAL(12,2) discount_amount, (p.list_price*((1+hash(i+121)%3)::BIGINT)-round(p.list_price*((1+hash(i+121)%3)::BIGINT)*(hash(i+181)%21)/100.0,2))::DECIMAL(12,2) net_amount FROM range(1,3000001)t(i) JOIN products p ON p.product_id=(1+hash(i+211)%50000)::BIGINT`,
`CREATE OR REPLACE TABLE orders AS SELECT a.order_id, ((1+hash(a.order_id+307)%150000)::BIGINT)::INTEGER customer_id, (DATE '2025-01-01'+(hash(a.order_id+331)%365)::INTEGER) order_date, list_extract(['web','mobile_app','marketplace'],(1+hash(a.order_id+353)%3)::BIGINT) channel, CASE WHEN hash(a.order_id+373)%100<5 THEN 'cancelled' WHEN hash(a.order_id+373)%100<12 THEN 'returned' ELSE 'completed' END status, a.net_amount::DECIMAL(14,2) net_amount, round(a.net_amount*.08,2)::DECIMAL(14,2) tax_amount, (CASE WHEN a.net_amount>=150 THEN 0 ELSE 6.99 END)::DECIMAL(12,2) shipping_amount FROM (SELECT order_id,sum(net_amount) net_amount FROM order_items GROUP BY order_id)a ORDER BY order_date,order_id`,
`CREATE OR REPLACE TABLE payments AS SELECT order_id payment_id,order_id,order_date payment_date,list_extract(['card','wallet','bank_transfer'],(1+hash(order_id+397)%3)::BIGINT) payment_method,CASE WHEN status='cancelled' THEN 'void' WHEN status='returned' THEN 'refunded' ELSE 'captured' END status,(net_amount+tax_amount+shipping_amount)::DECIMAL(14,2) amount FROM orders`,
`CREATE OR REPLACE TABLE shipments AS SELECT order_id shipment_id,order_id, (order_date+1)::DATE shipped_date, (order_date+(2+hash(order_id+419)%6)::INTEGER)::DATE delivered_date,list_extract(['Standard','Express','Economy'],(1+hash(order_id+433)%3)::BIGINT) carrier, CASE WHEN status='returned' THEN 'returned' WHEN status='cancelled' THEN 'cancelled' ELSE 'delivered' END status FROM orders WHERE order_id<=850000`,
`CREATE OR REPLACE TABLE sessions AS SELECT i::INTEGER session_id,(CASE WHEN i<=1000000 THEN o.customer_id ELSE (1+hash(i+461)%150000)::BIGINT END)::INTEGER customer_id,(CASE WHEN i<=1000000 THEN o.order_date ELSE DATE '2025-01-01'+(hash(i+487)%365)::INTEGER END)::DATE session_date,list_extract(['organic','paid_search','social','email','direct'],(1+hash(i+503)%5)::BIGINT) traffic_source,list_extract(['mobile','desktop','tablet'],(1+hash(i+521)%3)::BIGINT) device,((1+hash(i+541)%18)::BIGINT)::INTEGER page_views,CASE WHEN i<=1000000 THEN i::INTEGER ELSE NULL END order_id FROM range(1,3949586)t(i) LEFT JOIN orders o ON o.order_id=i ORDER BY session_date,session_id`
];
for(const sql of sqls){console.log(sql.split(' AS ')[0]);await c.run(sql);}
await c.run('ANALYZE; CHECKPOINT');const names=['regions','categories','products','customers','calendar','order_items','orders','payments','shipments','sessions'];const tables=[];for(const name of names){const rows=(await c.runAndReadAll(`SELECT count(*)::INTEGER n FROM ${name}`)).getRowObjects()[0].n;const columns=(await c.runAndReadAll(`DESCRIBE ${name}`)).getRowObjectsJson().map(r=>({name:r.column_name,type:r.column_type}));tables.push({name,rows,columns});}
c.closeSync();db.closeSync();const size=(await stat(`${dir}/ecommerce.duckdb`)).size;
const rules=["All records are synthetic, reproducible demo data for calendar year 2025; all monetary amounts are USD.","Table grains: orders/payments one row per order; order_items exactly three rows per order; shipments one row for each of 850000 orders; sessions one row per session.","Sales/revenue means SUM(orders.net_amount) WHERE orders.status='completed'. Excludes tax/shipping and cancelled/returned orders. Gross booked sales includes all statuses only if explicitly requested.","Orders count means COUNT(*) FROM orders, qualified by status when requested. AOV = completed revenue / completed order count.","Customers.customer_id links orders.customer_id and sessions.customer_id. customers.region_id links regions.region_id. order_items.order_id, payments.order_id and shipments.order_id link orders.order_id. products.product_id links order_items.product_id; products.category_id links categories.category_id.","Never sum orders.net_amount after joining to order_items; it repeats three times. For product/category revenue sum order_items.net_amount joined to orders filtered completed.","Payment amount includes net+tax+shipping, so it is not sales revenue. Payment status captured/void/refunded corresponds to completed/cancelled/returned orders.","Traffic = COUNT(*) FROM sessions. Conversion = count(sessions.order_id) / count(*) * 100; it includes placed orders of all statuses. For completed conversion join orders and explicitly filter status.","For a single date return one aggregate and display number unless a breakdown is requested. For temporal questions default to daily line chart; use monthly grouping for full-year requests.","Date filters on orders use order_date; sessions use session_date. Latest demo date is 2025-12-31. Relative last-7-days means 2025-12-25 through 2025-12-31 inclusive.","Read-only SELECT/CTE queries only. Return columns label (text), value (numeric), optional secondary (numeric). Charts <= 1000 groups. No external files, extensions, system tables, or network operations."];
const schema={name:'Demo e-commerce',version:'2025-v1',period:{start:'2025-01-01',end:'2025-12-31'},synthetic:true,currency:'USD',totalRows:tables.reduce((a,t)=>a+t.rows,0),databaseBytes:size,tables,rules,generatedSeconds:Math.round((performance.now()-start)/1000)};await writeFile(`${dir}/schema.json`,JSON.stringify(schema,null,2));console.log(JSON.stringify({totalRows:schema.totalRows,databaseBytes:size,generationSeconds:schema.generatedSeconds}));
