steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', 'server/Dockerfile', '-t', 'europe-west1-docker.pkg.dev/striking-loop-447915-q3/cloud-run-source-deploy/liveanalyst-duckdb:v1', '.']
images:
  - europe-west1-docker.pkg.dev/striking-loop-447915-q3/cloud-run-source-deploy/liveanalyst-duckdb:v1
options:
  machineType: E2_HIGHCPU_8
